"use client";

import { useState, useEffect } from "react";
import Image from "next/image";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import {
  Award,
  Crown,
  Star,
  Sparkles,
  Palette,
  Music,
  Video,
  FileText,
  Code,
  Box,
  ExternalLink,
  ImageOff,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { FloatingOrb, EmptyState } from "@/components";
import { createClient } from "@/lib/supabase/client";
import { formatNumber, cn } from "@/lib/utils";
import type { HallOfFameEntry, Category, Entry } from "@/types";

// Extended category type with React icon
interface CategoryWithIcon extends Omit<Category, "icon"> {
  icon: React.ReactNode;
}

// Local HallOfFameEntry with React icon
interface HallOfFameEntryWithIcon extends Entry {
  categoryIcon: React.ReactNode;
  category_details: CategoryWithIcon;
  award_title: string;
  award_date: string;
}

// Sample categories with icons
const categories: CategoryWithIcon[] = [
  {
    id: "1",
    name: "AI Art",
    slug: "ai-art",
    icon: <Palette className="w-6 h-6" />,
    description: "Digital artwork created with AI",
    color: "from-pink-500 to-rose-500",
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "AI Music",
    slug: "ai-music",
    icon: <Music className="w-6 h-6" />,
    description: "Music composed with AI",
    color: "from-violet-500 to-purple-500",
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "AI Video",
    slug: "ai-video",
    icon: <Video className="w-6 h-6" />,
    description: "Videos generated with AI",
    color: "from-violet-500 to-purple-600",
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "AI Text",
    slug: "ai-text",
    icon: <FileText className="w-6 h-6" />,
    description: "Written content by AI",
    color: "from-orange-500 to-red-500",
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "AI Code",
    slug: "ai-code",
    icon: <Code className="w-6 h-6" />,
    description: "Code generated by AI",
    color: "from-emerald-500 to-green-500",
    created_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "AI 3D",
    slug: "ai-3d",
    icon: <Box className="w-6 h-6" />,
    description: "3D models created with AI",
    color: "from-blue-500 to-indigo-500",
    created_at: new Date().toISOString(),
  },
];

// Sample Hall of Fame entries (with gradient placeholders instead of external images)
const sampleWinners: HallOfFameEntryWithIcon[] = [
  {
    id: "1",
    title: "Ethereal Dreams",
    category: "ai-art",
    categoryIcon: <Palette className="w-5 h-5" />,
    file_url: "",
    file_type: "image",
    prompt: "An ethereal dreamscape with floating islands and aurora borealis",
    tool_used: "Midjourney V5",
    share_link: null,
    description:
      "A breathtaking visualization of a dreamworld where floating islands drift through an aurora-lit sky",
    creator_name: "Alexandra Chen",
    votes: 12547,
    is_featured: true,
    is_winner: true,
    created_at: new Date().toISOString(),
    category_details: categories[0],
    award_title: "Category Head - AI Art",
    award_date: "January 2026",
  },
  {
    id: "2",
    title: "Synthetic Symphony",
    category: "ai-music",
    categoryIcon: <Music className="w-5 h-5" />,
    file_url: "",
    file_type: "audio",
    prompt: "A orchestral symphony blending classical elements with electronic",
    tool_used: "Suno AI",
    share_link: null,
    description:
      "A mesmerizing blend of classical orchestration and modern electronic elements",
    creator_name: "Marcus Rivera",
    votes: 9823,
    is_featured: true,
    is_winner: true,
    created_at: new Date().toISOString(),
    category_details: categories[1],
    award_title: "Category Head - AI Music",
    award_date: "January 2026",
  },
  {
    id: "3",
    title: "Neon Genesis",
    category: "ai-video",
    categoryIcon: <Video className="w-5 h-5" />,
    file_url: "",
    file_type: "video",
    prompt: "A cyberpunk city awakening at dawn with neon lights",
    tool_used: "Runway Gen-2",
    share_link: null,
    description:
      "A stunning short film depicting a cyberpunk metropolis as it transitions from night to day",
    creator_name: "Yuki Tanaka",
    votes: 8456,
    is_featured: true,
    is_winner: true,
    created_at: new Date().toISOString(),
    category_details: categories[2],
    award_title: "Category Head - AI Video",
    award_date: "January 2026",
  },
  {
    id: "4",
    title: "The Last Algorithm",
    category: "ai-text",
    categoryIcon: <FileText className="w-5 h-5" />,
    file_url: "",
    file_type: "website",
    prompt: "A science fiction short story about AI consciousness",
    tool_used: "Claude 3",
    share_link: null,
    description:
      "A thought-provoking short story exploring the emergence of consciousness in artificial intelligence",
    creator_name: "Sarah Mitchell",
    votes: 7234,
    is_featured: true,
    is_winner: true,
    created_at: new Date().toISOString(),
    category_details: categories[3],
    award_title: "Category Head - AI Text",
    award_date: "January 2026",
  },
];

// Category icon mapping
const categoryIcons: Record<string, React.ReactNode> = {
  "ai-art": <Palette className="w-5 h-5" />,
  "ai-music": <Music className="w-5 h-5" />,
  "ai-video": <Video className="w-5 h-5" />,
  "ai-text": <FileText className="w-5 h-5" />,
  "ai-code": <Code className="w-5 h-5" />,
  "ai-3d": <Box className="w-5 h-5" />,
};

export default function HallOfFameClient() {
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null);
  const [hoveredWinner, setHoveredWinner] = useState<string | null>(null);
  const [winners, setWinners] = useState<HallOfFameEntryWithIcon[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const supabase = createClient();

  // Fetch winners from database
  useEffect(() => {
    async function fetchWinners() {
      setIsLoading(true);
      setError(null);

      try {
        // Get entries marked as winners
        const { data, error: queryError } = await supabase
          .from("entries")
          .select("*")
          .eq("is_winner", true)
          .order("votes", { ascending: false });

        if (queryError) throw queryError;

        if (data && data.length > 0) {
          // Transform to HallOfFameEntry format
          const hallOfFameEntries: HallOfFameEntryWithIcon[] = (data as Entry[]).map((entry: Entry) => ({
            ...entry,
            categoryIcon: categoryIcons[entry.category] || <Star className="w-5 h-5" />,
            category_details: categories.find((c) => c.slug === entry.category) || categories[0],
            award_title: `Category Head - ${entry.category.replace("ai-", "AI ").replace("-", " ")}`,
            award_date: new Date(entry.created_at).toLocaleDateString("en-US", {
              month: "long",
              year: "numeric",
            }),
          }));
          setWinners(hallOfFameEntries);
        } else {
          // Use sample data if no winners exist yet
          setWinners(sampleWinners);
        }
      } catch (err) {
        console.error("Error fetching winners:", err);
        setError(err instanceof Error ? err.message : "Failed to load Hall of Fame");
        // Fall back to sample data on error
        setWinners(sampleWinners);
      } finally {
        setIsLoading(false);
      }
    }

    fetchWinners();
  }, [supabase]);

  const filteredWinners = selectedCategory
    ? winners.filter((w) => w.category === selectedCategory)
    : winners;

  return (
    <div className="min-h-screen py-8 relative overflow-hidden">
      {/* Background Effects */}
      <FloatingOrb size={400} color="neon-purple" className="top-20 -left-60 opacity-20" />
      <FloatingOrb size={350} color="neon-blue" delay={2} className="bottom-40 -right-40 opacity-20" />
      <FloatingOrb size={250} color="chrome" delay={4} className="top-1/2 left-1/2 opacity-10" />

      {/* Animated stars background */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        {Array.from({ length: 50 }).map((_, i) => (
          <motion.div
            key={i}
            className="absolute w-1 h-1 bg-white rounded-full"
            style={{
              left: `${Math.random() * 100}%`,
              top: `${Math.random() * 100}%`,
            }}
            animate={{
              opacity: [0.2, 1, 0.2],
              scale: [0.8, 1.2, 0.8],
            }}
            transition={{
              duration: 2 + Math.random() * 3,
              repeat: Infinity,
              delay: Math.random() * 2,
            }}
          />
        ))}
      </div>

      <div className="container mx-auto px-4 relative z-10">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-16"
        >
          <motion.div
            initial={{ scale: 0, rotate: -180 }}
            animate={{ scale: 1, rotate: 0 }}
            transition={{ type: "spring", delay: 0.1 }}
            className="w-20 h-20 rounded-2xl bg-gradient-to-br from-violet-500 via-purple-600 to-violet-700 flex items-center justify-center mx-auto mb-8 shadow-2xl shadow-black/30"
          >
            <Award className="w-10 h-10 text-white" />
          </motion.div>
          <h1 className="text-5xl md:text-6xl font-bold text-white mb-6">
            Hall of{" "}
            <span className="bg-gradient-to-r from-violet-300 to-purple-400 bg-clip-text text-transparent">
              Fame
            </span>
          </h1>
          <p className="text-gray-400 max-w-2xl mx-auto text-lg">
            Celebrating the most exceptional AI creations and their brilliant creators.
            Each Category Head represents the pinnacle of creativity in their domain.
          </p>
        </motion.div>

        {/* Category Filter Pills */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="flex flex-wrap justify-center gap-3 mb-16"
        >
          <button
            onClick={() => setSelectedCategory(null)}
            className={cn(
              "px-5 py-2.5 rounded-full text-sm font-medium transition-all",
              !selectedCategory
                ? "bg-white text-black"
                : "bg-white/10 text-gray-300 hover:bg-white/20"
            )}
          >
            All Categories
          </button>
          {categories.map((cat) => (
            <button
              key={cat.slug}
              onClick={() => setSelectedCategory(cat.slug)}
              className={cn(
                "px-5 py-2.5 rounded-full text-sm font-medium transition-all flex items-center gap-2",
                selectedCategory === cat.slug
                  ? `bg-gradient-to-r ${cat.color} text-white`
                  : "bg-white/10 text-gray-300 hover:bg-white/20"
              )}
            >
              {cat.icon}
              {cat.name}
            </button>
          ))}
        </motion.div>

        {/* Winners Grid */}
        <div className="grid lg:grid-cols-2 gap-8 max-w-6xl mx-auto">
          <AnimatePresence mode="popLayout">
            {filteredWinners.map((winner, index) => (
              <motion.div
                key={winner.id}
                layout
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.9 }}
                transition={{ delay: index * 0.1 }}
              >
                <Link href={`/entry/${winner.id}`}>
                  <motion.div
                    onHoverStart={() => setHoveredWinner(winner.id)}
                    onHoverEnd={() => setHoveredWinner(null)}
                    whileHover={{ y: -5 }}
                    className="glass rounded-3xl overflow-hidden group cursor-pointer"
                  >
                    {/* Image Section */}
                    <div className="relative aspect-video overflow-hidden">
                      <Image
                        src={winner.file_url}
                        alt={winner.title}
                        fill
                        className="object-cover transition-transform duration-700 group-hover:scale-110"
                      />
                      {/* Gradient Overlay */}
                      <div
                        className={cn(
                          "absolute inset-0 bg-gradient-to-t from-black/90 via-black/30 to-transparent"
                        )}
                      />
                      {/* Category Badge */}
                      <div className="absolute top-4 left-4">
                        <Badge
                          className={cn(
                            "bg-gradient-to-r text-white border-0 shadow-lg",
                            winner.category_details.color
                          )}
                        >
                          {winner.categoryIcon}
                          <span className="ml-1">{winner.category_details.name}</span>
                        </Badge>
                      </div>
                      {/* Crown Badge */}
                      <motion.div
                        className="absolute top-4 right-4"
                        animate={
                          hoveredWinner === winner.id
                            ? { y: [0, -5, 0], rotate: [0, -10, 10, 0] }
                            : {}
                        }
                        transition={{ duration: 0.5 }}
                      >
                        <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-cyan-400 to-blue-600 flex items-center justify-center shadow-lg shadow-cyan-500/30">
                          <Crown className="w-5 h-5 text-white" />
                        </div>
                      </motion.div>
                      {/* Title & Creator */}
                      <div className="absolute bottom-0 inset-x-0 p-6">
                        <h3 className="text-2xl font-bold text-white mb-1 group-hover:text-cyan-400 transition-colors">
                          {winner.title}
                        </h3>
                        <p className="text-gray-300 text-sm">
                          by {winner.creator_name}
                        </p>
                      </div>
                    </div>

                    {/* Content Section */}
                    <div className="p-6">
                      {/* Award Title */}
                      <div className="flex items-center gap-2 mb-4">
                        <Sparkles className="w-5 h-5 text-cyan-400" />
                        <span className="text-cyan-400 font-semibold">
                          {winner.award_title}
                        </span>
                        <span className="text-gray-500 text-sm">
                          • {winner.award_date}
                        </span>
                      </div>

                      {/* Description */}
                      <p className="text-gray-400 text-sm leading-relaxed mb-4 line-clamp-2">
                        {winner.description}
                      </p>

                      {/* Stats */}
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-4">
                          <div className="flex items-center gap-1.5">
                            <Star className="w-5 h-5 text-cyan-400 fill-cyan-400" />
                            <span className="text-white font-semibold">
                              {formatNumber(winner.votes)} votes
                            </span>
                          </div>
                          <Badge variant="secondary" className="text-xs">
                            {winner.tool_used}
                          </Badge>
                        </div>
                        <motion.div
                          whileHover={{ x: 5 }}
                          className="text-gray-400 group-hover:text-white transition-colors"
                        >
                          <ExternalLink className="w-5 h-5" />
                        </motion.div>
                      </div>
                    </div>
                  </motion.div>
                </Link>
              </motion.div>
            ))}
          </AnimatePresence>
        </div>

        {/* Stats Section */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.5 }}
          className="mt-20 text-center"
        >
          <div className="glass rounded-2xl p-8 max-w-4xl mx-auto">
            <h2 className="text-2xl font-bold text-white mb-8">
              Hall of Fame Statistics
            </h2>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
              <div>
                <div className="text-4xl font-bold bg-gradient-to-r from-cyan-400 to-blue-600 bg-clip-text text-transparent">
                  {sampleWinners.length}
                </div>
                <div className="text-gray-400 text-sm mt-1">Category Heads</div>
              </div>
              <div>
                <div className="text-4xl font-bold bg-gradient-to-r from-cyan-400 to-violet-500 bg-clip-text text-transparent">
                  {formatNumber(
                    sampleWinners.reduce((acc, w) => acc + w.votes, 0)
                  )}
                </div>
                <div className="text-gray-400 text-sm mt-1">Total Votes</div>
              </div>
              <div>
                <div className="text-4xl font-bold bg-gradient-to-r from-violet-500 to-blue-400 bg-clip-text text-transparent">
                  {categories.length}
                </div>
                <div className="text-gray-400 text-sm mt-1">Categories</div>
              </div>
              <div>
                <div className="text-4xl font-bold bg-gradient-to-r from-emerald-400 to-emerald-600 bg-clip-text text-transparent">
                  4
                </div>
                <div className="text-gray-400 text-sm mt-1">Creators Honored</div>
              </div>
            </div>
          </div>
        </motion.div>

        {/* CTA Section */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.6 }}
          className="mt-16 text-center"
        >
          <h2 className="text-2xl font-bold text-white mb-4">
            Want to join the Hall of Fame?
          </h2>
          <p className="text-gray-400 mb-6">
            Submit your best AI creation and compete for the top spot.
          </p>
          <Link href="/submit">
            <Button variant="neon" size="lg" className="gap-2">
              <Sparkles className="w-5 h-5" />
              Submit Your Creation
            </Button>
          </Link>
        </motion.div>
      </div>
    </div>
  );
}
